--- adding the schema for my supabase databse

--- Code to create table
CREATE TABLE Tbl_customer_appointments (
  appointment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_name text NOT NULL,
  patient_email text NOT NULL,
  appointment_at timestamptz NOT NULL,
  reason_for_visit text,
  created_at timestamptz DEFAULT now(),
  CHECK (patient_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

---Code to insert into table
INSERT INTO customer_appointments
(patient_name, patient_email, appointment_at, reason_for_visit)
VALUES
('Alice Johnson', 'alice.johnson@example.com', '2025-12-10 09:30:00+00', 'Routine Checkup'),
('Bob Smith', 'bob.smith@example.com', '2025-12-11 11:00:00+00', 'Flu Symptoms'),
('Carol White', 'carol.white@example.com', '2025-12-12 14:15:00+00', 'Follow-up Visit'),
('David Brown', 'david.brown@example.com', '2025-12-13 10:45:00+00', 'Blood Test'),
('Emma Davis', 'emma.davis@example.com', '2025-12-14 16:00:00+00', 'Consultation');
